apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector: # Define selector to filter labels => name, app in redis-pod.yml
    name: redis-pod
    app: demo-voting-app
