apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  # By default, type is ClusterIP type are only available within the cluster
  # to enable the service to be accessible outside the cluster.
  # we must set type is LoadBalancer
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector: # Define selector to filter labels => name, app in result-app-pod.yml
    name: result-app-pod
    app: demo-voting-app
